// <auto-generated />
namespace ProductivityTool.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v07 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v07));
        
        string IMigrationMetadata.Id
        {
            get { return "201901050603234_v0.7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
